title: Blanca Villanueva 
title_left: Blanca
title_right: Villanueva
email: blanca@cs.stanford.edu
url: villanuevab.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _bicv
github_username:  villanuevab

source      : / 
destination : /_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name: "Blanca Villanueva"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : blog
    title: Blog
  - slug : research
    title: Research 
  - slug : teaching 
    title: Teaching
  - slug : misc 
    title: Misc

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "vendor"]

# Build settings
permalink   : /:year/:month/:title/
markdown    : kramdown
highlighter : rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
